# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3803f17a89e890e216d0e67e30dd48b4cedfe14d242fc9365fc9a29fb5db999537c9354709a0fc38efd796946f6101769582324f1460b9ea5090792bc8c970ac

test:
  secret_key_base: 2ee44cc2377e9f3ff53339e26666c7982d1568442a0d57aae26bdae6e6a87c850ef6962d5f7e8b769d9bd9e3cfdbe008361c4f9d15692e7e095fd1f934cb5483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
